import os
import torch
import datetime

from stride import *

async def main(runtime):
    # Create the grid
    # specify the discretisation to be used
    shape = (320, 256)
    extra = (50, 50)
    absorbing = (40, 40)
    spacing = (0.5e-3, 0.5e-3)

    space = Space(shape=shape, extra=extra, absorbing=absorbing, spacing=spacing)

    start = 0.0
    step = 0.08e-6
    num = 2500

    time = Time(start=start, step=step, num=num)

    # Flag to decide whether to use the diffusion model in the FWI process or not
    USE_DIFFUSION_FWI = False  

    # Model name
    name = "VP_996782"
    input_dir = f"./exps/forward/{name}"
    output_dir = f"./exps/inverse/{name}" + ("_diffusion_fwi" if USE_DIFFUSION_FWI else "") 
    if os.path.exists(output_dir):
        output_dir += "_" + datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    os.makedirs(output_dir, exist_ok=True)

    # Create problem
    problem = Problem(
        name=name,
        space=space,
        time=time,
        input_folder=input_dir,
        output_folder=output_dir,
    )

    # Create medium
    # this is the speed of sound of the region of interest
    # vp contains a Numpy array with the velocity for every point on the grid
    # we create a water model with vp = 1500 m/s everywhere to start with
    vp = ScalarField.parameter(name="vp", grid=problem.grid, needs_grad=True)
    vp.fill(1500.0)

    problem.medium.add(vp)

    # Create transducers
    # we generally assume point transducers in simulation, but
    # in reality more complex transducer geometries are used
    problem.transducers.default()

    # Create geometry
    # this will make a ring of 256 transducers around the region of interest
    num_locations = 256
    problem.geometry.default(
        "elliptical",
        num_locations,
        radius=((space.limit[0] - 7.0e-3) / 2, (space.limit[1] - 5.0e-3) / 2),
    )

    # Create acquisitions
    # load the simulated observed file generated by the forward script
    problem.acquisitions.load(
        filename=f"{input_dir}/{name}-Acquisitions.h5",
    )

    # Plot
    # some plotting of what we have built so far
    problem.plot()

    # Create the PDE
    # the physics of our problem are represented by the iso-acoustic wave equation
    pde = IsoAcousticDevito.remote(grid=problem.grid, len=runtime.num_workers)

    # Create loss
    # there are potentially multiple loss functions we could use to run FWI,
    # but we will stick with the L2 Norm for now
    loss = L2DistanceLoss.remote(len=runtime.num_workers)

    # Create optimiser
    # to run the optimisation, we will use gradient descent with a fixed step size
    step_size = 5

    # we can use this syntax to do operations on the FWI gradient at every iteration
    process_grad = ProcessGlobalGradient()

    # add a box constraint: vp should be between 1480 and 3000 m/s(skull has higher velocity)
    process_model = ProcessModelIteration(min=1480.0, max=3000.0)

    # An optimisation loop is a fancy wrapper for a `for` loop
    optimisation_loop = OptimisationLoop()

    # FWI is a non-linear, non-convex optimisation problem, so to ensure convergence,
    # we start the inversion at low frequencies and add higher frequencies progressively
    # we call each of these frequency bands a block, and we run each block for a fixed
    # number of iterations
    max_freqs = [0.1e6, 0.2e6, 0.3e6, 0.35e6]
    num_blocks = len(max_freqs)
    block_iters = [40, 24, 24, 32]

    # ###### DEBUGGING
    # max_freqs = [0.1e6]
    # num_blocks = len(max_freqs)
    # block_iters = [1]


    ########################################################
    ############# Diffusion FWI Pipeline Setup #############
    ########################################################

    if USE_DIFFUSION_FWI:
        from diffusionfwi.fwi import DiffusionVpOperator
        from diffusionfwi.diffusion import DiffusionProcess
        from diffusionfwi.models import UNetAttnMoreD

        # Set up the diffusion process and model that we will use in the operator
        device = "cuda" if torch.cuda.is_available() else "cpu"
        diffusion_process = DiffusionProcess(T=1000, s=0.008, device=device)

        # Load the pre-trained diffusion model
        diffusion_model = UNetAttnMoreD(
            in_channels=1,
            out_channels=1,
            time_emb_dim=256,
        )
        ckpt_path = "/scratch_hive/dp4018/scripts/diffusion-fwi-2d/exps/diffusion/" \
                    "diffusion_fwi_2d/checkpoints/model_epoch_16.pth"
        
        diffusion_model.load_state_dict(
            torch.load(ckpt_path, map_location="cpu") # always force loading on CPU, to avoid GPU memory issues
        )
        diffusion_model.eval()

        scheduling_args = {
            "iters_to_run": [40, 64, 88, 99], # run diffusion roughly at the end of every block
            "t_starts": [900, 700, 500, 300], # reduce the strength of diffusion at every block
            "alphas": [0.3, 0.2, 0.15, 0.1],  # reduce the strength of blending at every block
        }

        # ###### DEBUGGING
        # scheduling_args = {
        #     "iters_to_run": [1], # run diffusion roughly at the end of every block
        #     "t_starts": [900], # reduce the strength of diffusion at every block
        #     "alphas": [1.],  # reduce the strength of blending at every block
        # }

        process_model.append(
            "diffusion",
            DiffusionVpOperator(
                input_dim=32,   # the dimension of the velocity model volume that will be fed into the diffusion model (after downsampling)
                original_dim=shape,  # the original dimension of the velocity model volume (before any downsampling)
                diffusion_model=diffusion_model,  # the diffusion model to use in the operator
                diffusion_process=diffusion_process,  # the diffusion process to use in the operator
                mask=None,  # a blending mask to be passed to the update function, if needed
                update_fn=None,  # a function to combine the original and generated volumes
                scheduling_args=scheduling_args,  # arguments for the diffusion-fwi scheduling
                total_iterations=sum(block_iters),  # total number of iterations for the whole FWI run
                device=device,
            ),
        )

    ########################################################
    ########################################################

    # Create the optimiser
    optimiser = GradientDescent(
        vp,
        step_size=step_size,
        process_grad=process_grad,
        process_model=process_model,
        dump_grad=True,
    )

    # running all shots in every iteration would be too costly,
    # so we run a subset of them (a batch)
    num_shots_per_iter = 32

    # ###### DEBUGGING
    # num_shots_per_iter = 2 

    for i, (block, freq) in enumerate(optimisation_loop.blocks(num_blocks, max_freqs)):
        # prepare some initial configuration for the block
        num_iters = block_iters[i]

        # inside the block, we run for a specific number of iterations
        for iteration in block.iterations(num_iters):
            # run one single iteration of FWI
            # vp.data will have been updated at the end of this call
            await adjoint(
                problem,
                pde,
                loss,
                optimisation_loop,
                optimiser,
                vp,
                num_iters=num_iters,
                select_shots=dict(num=num_shots_per_iter, randomly=True),
                f_max=freq,
                max_freqs=max_freqs,
                kernel="OT4",
                platform="nvidia-acc",
            )

            # save vp to disk after each iteration
            optimiser.dump(
                path=problem.output_folder,
                project_name=problem.name,
                version=iteration.abs_id + 1,
            )


if __name__ == "__main__":
    mosaic.run(main, log_level="perf")
