#!/bin/bash
#PBS -l select=1:ncpus=4:mem=512gb:ngpus=1
#PBS -l walltime=00:30:00
#PBS -N forward_script

# Activate environment
source ~/miniforge3/etc/profile.d/conda.sh
conda activate stride

module load NVHPC/25.1-CUDA-12.6.0
module load CUDA/12.6.0
cd "$PBS_O_WORKDIR"

# Load NVIDIA HPC SDK
export HPCSDK_HOME=/sw-eb/software/NVHPC/25.1-CUDA-12.6.0/Linux_x86_64/25.1
export NVHPC_CUDA_HOME=$HPCSDK_HOME/cuda
export CUDA_ROOT=$NVHPC_CUDA_HOME/bin
export PATH=$HPCSDK_HOME/compilers/bin/:$PATH
export LD_LIBRARY_PATH=$HPCSDK_HOME/compilers/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$NVHPC_CUDA_HOME/lib64/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$HPCSDK_HOME/math_libs/lib64/:$LD_LIBRARY_PATH
# Devito settings
export DEVITO_COMPILER=nvc
export DEVITO_LANGUAGE=openacc
export DEVITO_PLATFORM=nvidiaX

mrun -l python forward.py




