import numpy as np
import os
from stride import *


class DummyGradientOperation(Operator):

    def forward(self, grad, **kwargs):
        # `grad.data` is a Numpy array, and can be operated on as needed
        grad_data = grad.data
        grad_data = grad_data + 0.0
        # this method should return a new copy of the array
        new_grad = grad.alike(data=grad_data)
        return new_grad


async def main(runtime):
    np.random.seed(12345)

    # Create the grid
    # specify the discretisation to be used
    shape = (320, 256)
    extra = (50, 50)
    absorbing = (40, 40)
    spacing = (0.5e-3, 0.5e-3)

    space = Space(shape=shape, extra=extra, absorbing=absorbing, spacing=spacing)

    start = 0.0
    step = 0.08e-6
    num = 2500

    time = Time(start=start, step=step, num=num)

    # Create problem
    problem = Problem(name="anastasio2D", space=space, time=time)

    # Create medium
    # this is the speed of sound of the region of interest
    # vp contains a Numpy array with the velocity for every point on the grid
    vp = ScalarField.parameter(name="vp", grid=problem.grid, needs_grad=True)
    vp.fill(1500.0)

    problem.medium.add(vp)

    # Create transducers
    # we generally assume point transducers in simulation, but
    # in reality more complex transducer geometries are used
    problem.transducers.default()

    # Create geometry
    # this will make a ring of 256 transducers around the region of interest
    num_locations = 256
    problem.geometry.default(
        "elliptical",
        num_locations,
        radius=((space.limit[0] - 7.0e-3) / 2, (space.limit[1] - 5.0e-3) / 2),
    )

    # Create acquisitions
    # load the simulated observed file generated by the forward script
    problem.acquisitions.load(
        path=problem.output_folder, project_name=problem.name, version=0
    )

    # Plot
    # some plotting of what we have built so far
    problem.plot()

    # Create the PDE
    # the physics of our problem are represented by the iso-acoustic wave equation
    pde = IsoAcousticDevito.remote(grid=problem.grid, len=runtime.num_workers)

    # Create loss
    # there are potentially multiple loss functions we could use to run FWI,
    # but we will stick with the L2 Norm for now
    loss = L2DistanceLoss.remote(len=runtime.num_workers)

    # Create optimiser
    # to run the optimisation, we will use gradient descent with a fixed step size
    step_size = 5

    # we can use this syntax to do operations on the FWI gradient at every iteration
    process_grad = ProcessGlobalGradient()
    process_grad.append("dummy_gradient_operation", DummyGradientOperation())

    # add a box constraint: vp should be between 1480 and 3000 m/s(skull has higher velocity)
    process_model = ProcessModelIteration(min=1480.0, max=3000.0)

    # create the optimiser
    optimiser = GradientDescent(
        vp,
        step_size=step_size,
        process_grad=process_grad,
        process_model=process_model,
        dump_grad=True,
    )

    # Run optimisation
    # an optimisation loop is a fancy wrapper for a `for` loop
    optimisation_loop = OptimisationLoop()

    # FWI is a non-linear, non-convex optimisation problem, so to ensure convergence,
    # we start the inversion at low frequencies and add higher frequencies progressively
    # we call each of these frequency bands a block, and we run each block for a fixed
    # number of iterations
    max_freqs = [0.1e6, 0.2e6, 0.3e6, 0.35e6]
    num_blocks = len(max_freqs)
    block_iters = [40, 24, 24, 32]
    # num_iters = 24
    # running all shots in every iteration would be too costly,
    # so we run a subset of them (a batch)
    num_shots_per_iter = 32

    for i, (block, freq) in enumerate(optimisation_loop.blocks(num_blocks, max_freqs)):
        # prepare some initial configuration for the block
        num_iters = block_iters[i]
        operators = init_block(problem, optimiser, f_max=freq, max_freqs=max_freqs)

        # inside the block, we run for a specific number of iterations
        for iteration in block.iterations(num_iters):
            # run one single iteration of FWI
            # vp.data will have been updated at the end of this call
            await run_iteration(
                problem,
                pde,
                loss,
                optimisation_loop,
                optimiser,
                operators,
                vp,
                select_shots=dict(num=num_shots_per_iter, randomly=True),
                f_max=freq,
                max_freqs=max_freqs,
                iteration=iteration,
                kernel="OT4",
                platform="nvidia-acc",
            )

            # save vp to disk after this iteration
            optimiser.dump(
                path=problem.output_folder,
                project_name=problem.name,
                version=iteration.abs_id + 1,
            )

    vp.plot()


def init_block(problem, optimiser, **kwargs):
    """

    Parameters
    ----------
    problem : Problem
        Problem to run the optimisation on.
    optimiser : LocalOptimiser
        Local optimiser associated with the variable for which we are inverting.
    f_min : float, optional
        Min. frequency to filter wavelets and data with. If not given, no high-pass filter
        is applied.
    f_max : float, optional
        Max. frequency to filter wavelets and data with. If not given, no low-pass filter
        is applied.

    Returns
    -------
    list
        List of operators created for the current block.

    """
    runtime = mosaic.runtime()

    f_min = kwargs.pop("f_min", None)
    f_max = kwargs.pop("f_max", None)

    filter_wavelets_relaxation = 0.75
    filter_traces_relaxation = 0.75
    process_wavelets = ProcessWavelets.remote(
        f_min=f_min,
        f_max=f_max,
        filter_traces=True,
        filter_relaxation=filter_wavelets_relaxation,
        len=runtime.num_workers,
        **kwargs,
    )
    process_observed = ProcessObserved.remote(
        f_min=f_min,
        f_max=f_max,
        filter_traces=True,
        filter_relaxation=filter_wavelets_relaxation,
        len=runtime.num_workers,
        **kwargs,
    )
    process_wavelets_observed = ProcessWaveletsObserved.remote(
        f_min=f_min, f_max=f_max, filter_traces=True, len=runtime.num_workers, **kwargs
    )
    process_traces = ProcessTraces.remote(
        f_min=f_min,
        f_max=f_max,
        filter_traces=True,
        filter_relaxation=filter_traces_relaxation,
        len=runtime.num_workers,
        **kwargs,
    )

    problem.acquisitions.reset_selection()

    if optimiser.reset_block:
        optimiser.reset()

    return process_wavelets, process_observed, process_wavelets_observed, process_traces


async def run_iteration(
    problem, pde, loss, optimisation_loop, optimiser, operators, *args, **kwargs
):
    """
    Use a ``problem`` forward using a given ``pde``. The given ``args`` and ``kwargs``
    will be passed on to the PDE.

    Parameters
    ----------
    problem : Problem
        Problem to run the optimisation on.
    pde : Operator
        PDE operator to run for each shot in the problem.
    loss : Operator
        Loss function operator.
    optimisation_loop : OptimisationLoop
        Optimisation loop.
    optimiser : LocalOptimiser
        Local optimiser associated with the variable for which we are inverting.
    operators : list
        List of operators already created for the current block.
    select_shots : dict, optional
        Rules for selecting available shots per iteration, defaults to taking all shots. For
        details on this see :func:`~stride.problem.acquisitions.Acquisitions.select_shot_ids`.
    f_min : float, optional
        Min. frequency to filter wavelets and data with. If not given, no high-pass filter
        is applied.
    f_max : float, optional
        Max. frequency to filter wavelets and data with. If not given, no low-pass filter
        is applied.
    iteration : Iteration
        Current iteration object
    args : optional
        Extra positional arguments for the operators.
    kwargs : optional
        Extra keyword arguments for the operators.

    Returns
    -------

    """
    logger = mosaic.logger()
    runtime = mosaic.runtime()

    select_shots = kwargs.pop("select_shots", {})
    iteration = kwargs.pop("iteration", None)
    block = iteration.block

    # gather operators already created
    process_wavelets, process_observed, process_wavelets_observed, process_traces = (
        operators
    )

    # prepare GPU configuration
    platform = kwargs.get("platform", "cpu")
    using_gpu = "nvidia" in platform or "gpu" in platform
    if using_gpu:
        devices = kwargs.pop("devices", None)
        num_gpus = mosaic.utils.gpu_count() if devices is None else len(devices)
        devices = list(range(num_gpus)) if devices is None else devices

    # clear gradient and reset optimiser if needed
    optimiser.clear_grad()
    if optimiser.reset_iteration:
        optimiser.reset()

    # pre-distribute relevant parameters to parallel processes
    published_args = [runtime.put(each, publish=True) for each in args]
    published_args = await asyncio.gather(*published_args)

    logger.perf(
        "Starting iteration %d (out of %d), "
        "block %d (out of %d)"
        % (
            iteration.id + 1,
            block.num_iterations,
            block.id + 1,
            optimisation_loop.num_blocks,
        )
    )

    # select a subset of all shots (a batch)
    shot_ids = problem.acquisitions.select_shot_ids(**select_shots)
    num_shots = len(shot_ids)
    shot_dir = problem.output_folder
    iter_shot_file = os.path.join(shot_dir, f"shotids-iter-{iteration.abs_id+1}.npy")
    np.save(iter_shot_file, shot_ids)

    # another fancy for loop that runs in parallel
    @runtime.async_for(shot_ids, safe=False)
    async def loop(worker, shot_id):
        _kwargs = kwargs.copy()

        logger.perf("\n")
        logger.perf(
            "Giving shot %d to %s (%d out of %d)"
            % (shot_id, worker.uid, iteration.num_submitted, num_shots)
        )

        sub_problem = problem.sub_problem(shot_id)
        iteration.add_submitted(sub_problem.shot)
        wavelets = sub_problem.shot.wavelets
        observed = sub_problem.shot.observed

        if wavelets is None:
            raise RuntimeError("Shot %d has no wavelet data" % shot_id)

        if observed is None:
            raise RuntimeError("Shot %d has no observed data" % shot_id)

        if using_gpu:
            deviceid = devices[worker.indices[1] % num_gpus]
            if platform in ["nvidia-acc", "nvidia-cuda"]:
                devito_args = _kwargs.get("devito_args", {}).copy()
                devito_args["deviceid"] = deviceid
                _kwargs["devito_args"] = devito_args
            elif platform == "gpu":
                _kwargs["deviceid"] = deviceid
            else:
                raise ValueError("Unknown platform %s" % platform)

        # pre-process wavelets and observed traces
        wavelets = process_wavelets(
            wavelets,
            iteration=iteration,
            problem=sub_problem,
            runtime=worker,
            **_kwargs,
        )
        observed = process_observed(
            observed,
            iteration=iteration,
            problem=sub_problem,
            runtime=worker,
            **_kwargs,
        )
        processed = process_wavelets_observed(
            wavelets,
            observed,
            iteration=iteration,
            problem=sub_problem,
            runtime=worker,
            **_kwargs,
        )
        wavelets = processed.outputs[0]
        observed = processed.outputs[1]

        # run PDE
        modelled = pde(
            wavelets,
            *published_args,
            iteration=iteration,
            problem=sub_problem,
            runtime=worker,
            **_kwargs,
        )

        # post-process modelled and observed traces
        scale_to = sub_problem.shot.observed
        traces = process_traces(
            modelled,
            observed,
            scale_to=scale_to,
            iteration=iteration,
            problem=sub_problem,
            runtime=worker,
            **_kwargs,
        )
        modelled = traces.outputs[0]
        observed = traces.outputs[1]

        # calculate loss
        fun = loss(
            modelled,
            observed,
            keep_residual=False,
            iteration=iteration,
            problem=sub_problem,
            runtime=worker,
            **_kwargs,
        )

        # run adjoint
        fun_value = await fun.remote.adjoint(**_kwargs).result()

        iteration.add_loss(fun_value)
        logger.perf("Functional value for shot %d: %s" % (shot_id, fun_value))

        iteration.add_completed(sub_problem.shot)
        logger.perf(
            "Retrieved gradient for shot %d (%d out of %d)"
            % (sub_problem.shot_id, iteration.num_completed, num_shots)
        )

    await loop

    # take a step of gradient descent
    f_min = kwargs.pop("f_min", None)
    f_max = kwargs.pop("f_max", None)
    await optimiser.step(
        iteration=iteration,
        problem=problem,
        f_min=f_min,
        f_max=f_max,
        filter_relaxation=0.75,
        **kwargs,
    )

    if iteration.prev_run is not None:
        prev_loss = iteration.prev_run.total_loss
        prev_loss = " [previous loss %e]" % prev_loss
    else:
        prev_loss = ""

    iter_loss = os.path.join(
        problem.output_folder, f"loss_iter-{iteration.abs_id+1}.npy"
    )
    np.save(iter_loss, iteration.total_loss)
    logger.perf(
        "Done iteration %d (out of %d), "
        "block %d (out of %d) - Total loss %e%s"
        % (
            iteration.id + 1,
            block.num_iterations,
            block.id + 1,
            optimisation_loop.num_blocks,
            iteration.total_loss,
            prev_loss,
        )
    )
    logger.perf("====================================================================")

    iteration.clear_run()


if __name__ == "__main__":
    mosaic.run(main)
